remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-gist
- jekyll-mentions
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-avatar
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-readme-index
- jekyll-commonmark-ghpages
- jekyll-include-relative
- jekyll-remote-theme
- jekyll-theme-primer
- jekyll-theme-architect
- jekyll-theme-cayman
- jekyll-theme-dinky
- jekyll-theme-hacker
- jekyll-theme-leap-day
- jekyll-theme-merlot
- jekyll-theme-midnight
- jekyll-theme-minimal
- jekyll-theme-modernist
- jekyll-theme-slate
- jekyll-theme-tactile
- jekyll-theme-time-machine
- jekyll-theme-hacker
- jekyll-theme-primer
- jekyll-theme-architect
- jekyll-theme-cayman
- jekyll-theme-dinky
